drm/amdkcl: correct check of drm_color_lut for old kernel.
At present drm-color-lut-size.m4 cannot reflect the true
situation about drm_color_lut existence for old kernels,
The bad judgment attributes to below build error:
~~~
include/drm/drm_color_mgmt.h:31:5: error: ‘struct drm_crtc’
declared inside parameter list [-Werror]
uint gamma_lut_size);
^
include/drm/drm_color_mgmt.h:31:5: error: its scope is only
this definition or declaration, which is probably not what
you want [-Werror]
include/drm/drm_color_mgmt.h:34:6: error: ‘struct drm_crtc’
declared inside parameter list [-Werror]
int gamma_size);
~~~
the solution is to add drm_crtc declaration in M4 file. In
later kernel drm_color_mgmt.h has struct drm_crtc declaration

Change-Id: I308711d611b1c2e58bba89e6fa884e746a60524c
Signed-off-by: Jiansong Chen <Jiansong.Chen@amd.com>
Reviewed-by: Jack Gui <Jack.Gui@amd.com>