drm/amd/autoconf: fix compiling error in sled15sp1
 /var/lib/dkms/amdgpu-pro/1.0/build/amd/amdgpu/../display/amdgpu_dm/amdgpu_dm.h:376:31: note: in expansion of macro ‘container_of’
  #define to_dm_atomic_state(x) container_of(x, struct dm_atomic_state, base)
                                ^~~~~~~~~~~~
 /var/lib/dkms/amdgpu-pro/1.0/build/amd/amdgpu/../display/amdgpu_dm/amdgpu_dm.c:7309:37: note: in expansion of macro ‘to_dm_atomic_state’
   struct dm_atomic_state *dm_state = to_dm_atomic_state((struct drm_private_state*)state);
                                      ^
   CC [M]  /var/lib/dkms/amdgpu-pro/1.0/build/amd/amdgpu/../display/dc/bios/command_table.o
 /var/lib/dkms/amdgpu-pro/1.0/build/amd/amdgpu/../display/amdgpu_dm/amdgpu_dm.c: In function ‘dm_update_plane_state’:
 /usr/src/linux-4.12.14-195/include/linux/compiler.h:563:38: error: call to ‘__compiletime_assert_7633’ declared with attribute error: pointer type mismatch in container_of()
   _compiletime_assert(condition, msg, __compiletime_assert_, __LINE__)
                                       ^
 /usr/src/linux-4.12.14-195/include/linux/compiler.h:543:4: note: in definition of macro ‘__compiletime_assert’
     prefix ## suffix();    \
     ^~~~~~
 /usr/src/linux-4.12.14-195/include/linux/compiler.h:563:2: note: in expansion of macro ‘_compiletime_assert’
   _compiletime_assert(condition, msg, __compiletime_assert_, __LINE__)
   ^~~~~~~~~~~~~~~~~~~
 /usr/src/linux-4.12.14-195/include/linux/build_bug.h:44:37: note: in expansion of macro ‘compiletime_assert’
  #define BUILD_BUG_ON_MSG(cond, msg) compiletime_assert(!(cond), msg)
                                      ^~~~~~~~~~~~~~~~~~
 /usr/src/linux-4.12.14-195/include/linux/kernel.h:891:2: note: in expansion of macro ‘BUILD_BUG_ON_MSG’
   BUILD_BUG_ON_MSG(!__same_type(*(ptr), ((type *)0)->member) && \
   ^~~~~~~~~~~~~~~~
 /var/lib/dkms/amdgpu-pro/1.0/build/amd/amdgpu/../display/amdgpu_dm/amdgpu_dm.h:376:31: note: in expansion of macro ‘container_of’
  #define to_dm_atomic_state(x) container_of(x, struct dm_atomic_state, base)
                                ^~~~~~~~~~~~
 /var/lib/dkms/amdgpu-pro/1.0/build/amd/amdgpu/../display/amdgpu_dm/amdgpu_dm.c:7633:37: note: in expansion of macro ‘to_dm_atomic_state’
   struct dm_atomic_state *dm_state = to_dm_atomic_state((struct drm_private_state*)state);
                                      ^
   CC [M]  /var/lib/dkms/amdgpu-pro/1.0/build/amd/amdgpu/../display/dc/bios/command_table_helper.o

This reverts commit b852a451739945dd14099a6a8ba5449bb873bcd0.

Signed-off-by: Slava Grigorev <slava.grigorev@amd.com>
Signed-off-by: Anatoli Antonovitch <anatoli.antonovitch@amd.com>
Signed-off-by: chen gong <curry.gong@amd.com>
Signed-off-by: Yifan Zhang <yifan1.zhang@amd.com>
Reviewed-by: Flora Cui <flora.cui@amd.com>