drm/amd/display: Fix guarding of 'if (dc->debug.visual_confirm)'
Presumably the author intended to guard the for loop with
condition 'dc->res_pool->pipe_count' under 'if (dc->debug.visual_confirm)'
so that's what I'm changing the code to. Hopefully to do the right thing.

Fixes the below compilation error:

drivers/gpu/drm/amd/amdgpu/../display/dc/core/dc.c:3546:3: error: misleading indentation; statement is not part of the previous 'if' [-Werror,-Wmisleading-indentation]
                for (i = 0; i < surface_count; i++) {
                ^
drivers/gpu/drm/amd/amdgpu/../display/dc/core/dc.c:3538:2: note: previous statement is here
        if (dc->debug.visual_confirm)
        ^

Fixes: 25e1a6115fc2 ("drm/amd/display: Refactor fast update to use new HWSS build sequence")
Suggested-by: Alvin Lee <alvin.lee2@amd.com>
Cc: Stylon Wang <stylon.wang@amd.com>
Cc: Alvin Lee <alvin.lee2@amd.com>
Cc: Jun Lei <jun.lei@amd.com>
Cc: Rodrigo Siqueira <Rodrigo.Siqueira@amd.com>
Cc: Aurabindo Pillai <aurabindo.pillai@amd.com>
Cc: Alex Deucher <alexander.deucher@amd.com>
Reviewed-by: Hamza Mahfooz <hamza.mahfooz@amd.com>
Signed-off-by: Srinivasan Shanmugam <srinivasan.shanmugam@amd.com>
Signed-off-by: Hamza Mahfooz <hamza.mahfooz@amd.com>