drm/amd/autoconf: fix the vulkan cts error
yifan@yifan-System-Product-Name:~/cqetest$ vulkaninfo
ERROR: [Loader Message] Code 0 : /opt/amdgpu-pro/lib/i386-linux-gnu/amdvlk32.so: wrong ELF class: ELFCLASS32
/home/lunarg/sdk-build/Vulkan-Tools/vulkaninfo/vulkaninfo.c:923: failed with VK_ERROR_OUT_OF_HOST_MEMORY

This reverts commit 8e162714eeea8bb1539c45d06f845c12c3ea39a6.

Change-Id: I71fb7a9231bbee7848a868cb128a516e84f1f5c4
Signed-off-by: Yifan Zhang <yifan1.zhang@amd.com>