drm/amdkcl: Fix SLE15 DKMS build
[Why]
When dkms builds on SUSE15 target it fails due to
compilation errors:
1. amdgpu_gem_userptr_ioctl@amdgpu_gem.c:
error: too many arguments to function ‘release_pages’
2. amdgpu_dm.c: errors:
(a)static declaration of ‘drm_mode_is_420_only’
   follows non-static declaration;
(b)too few arguments to function ‘drm_mode_object_find’

[How]
Guard discrepancies with OS_NAME_SUSE_15 precompile flag

Change-Id: I850c595630ed39550e9a712a5f78d426990d09db
Signed-off-by: Roman Li <Roman.Li@amd.com>
Reviewed-by: Kevin Wang <Kevin1.Wang@amd.com>