drm/amdkcl: fix compile error if CONFIG_CC_IS_GCC not defined
It is noticed that CONFIG_CC_IS_GCC is not defined on some old distro,
such as rehl7.7, rehl7.6, ubuntu14.04 and so on, with patch
“commit 14f86470b576541b2536280ad0580058d7ec7a77” still has compile error,
error: -mpreferred-stack-boundary=3 is not between 4 and 12

It is reasonable to remove CONFIG_CC_IS_GCC check.

Change-Id: I5d6d482afd03ba82541af3219598bdd393f72b11
Signed-off-by: Stanley.Yang <Stanley.Yang@amd.com>
Reviewed-by: Rui Teng <rui.teng@amd.com>