drm/amdkcl: fix compiling error of deallocate_mst_payload_with_temp_drm_wa()
It's caused by ddb61e9c2506851166051a7d7c6257a3be0405c7
"drm/amdkcl: fix display dp mst malfunction"
This patch causes compiling error on RHEL9.x.
Error: unused function deallocate_mst_payload_with_temp_drm_wa()

Reviewed-by: Guchun Chen <guchun.chen@amd.com>
Signed-off-by: tiancyin <tianci.yin@amd.com>