drm/amdgpu: remove redundant variable declaration
building with gcc and W=1 reports
drivers/gpu/drm/amd/amdgpu/amdgpu_object.c:1618:15:
error: unused variable 'domain' [-Werror=unused-variable]
unsigned int domain;
             ^~~~~~

The variable domain is repeated, so remove it.

Fixes: d769528e4649 ("drm/amdgpu: add VISIBLE info in amdgpu_bo_print_info")
Signed-off-by: Bob Zhou <bob.zhou@amd.com>
Reviewed-by: Guchun Chen <guchun.chen@amd.com>
Reviewed-by: Srinivasan Shanmugam <srinivasan.shanmugam@amd.com>