Revert "drm/amdgpu/gmc: fix compiler errors [-Werror,-Wmissing-braces]"
This reverts commit 433020a1e55eb629a7e3f3722587ce72daa27919.

Didn't compile:

drivers/gpu/drm//amd/amdgpu/gmc_v9_0.c: In function ‘gmc_v9_0_process_interrupt’:
drivers/gpu/drm//amd/amdgpu/gmc_v9_0.c:325:32: error: ‘amdgpu_task_info’ undeclared (first use in this function)
   memset(&task_info, 0, sizeof(amdgpu_task_info));
                                ^~~~~~~~~~~~~~~~

Signed-off-by: Michel Dänzer <michel.daenzer@amd.com>