drm/amdkcl: [4.20] fix dkms build errors on customer kernel 5.0
list_bulk_move_tail redefinition error:
patch "list: introduce list_bulk_move_tail helper" introduce
list_bulk_move_tail from v4.20-rc1, so the kcl implementation
of list_bulk_move_tail should be constrained < v4.20 .

struct reservation_object has no member named "staged" error:
staged is referenced by _kcl_reservation_object_copy_fences and
_kcl_reservation_object_add_shared_fence, and this member variable
is removed by patch "dma-buf: remove shared fence staging in reservation
object" from v5.0-rc1.
reservation_object_copy_fences was introduced by "dma-buf: add
reservation_object_copy_fences (v2)" from v4.14-rc1, so
_kcl_reservation_object_copy_fences should be constrained < v4.14 .
reservation_object_add_shared_fence was introduced by "reservation:
update api and add some helpers" from v3.17-rc1, so
_kcl_reservation_object_add_shared_fence should be constrained < v3.17 .

Change-Id: Iadeeef6860cbccab304cea81633f599249ce8af7
Reviewed-by: changzhu <Changfeng.Zhu@amd.com>
Signed-off-by: Tianci Yin <tianci.yin@amd.com>