drm/amdkcl: fix peer direct support build failure
The patch fixes this issue by adjusting symbol resolution for peer direct support.
When HAVE_KFD_PEERDIRECT_SUPPORT is enabled, the build system now properly detects the presence
of the required symbols "ib_register_peer_memory_client" and "ib_unregister_peer_memory_client".

Previously, building the amdgpu module failed with the following errors:
ERROR: "ib_register_peer_memory_client" [/tmp/amd.C1mGku2S/amd/amdgpu/amdgpu.ko] undefined!
ERROR: "ib_unregister_peer_memory_client" [/tmp/amd.C1mGku2S/amd/amdgpu/amdgpu.ko] undefined!
This occurred during the modpost phase while building the kernel:
make[2]: *** [scripts/Makefile.modpost:94: __modpost] Error 1
make[1]: *** [Makefile:1659: modules] Error 2

Signed-off-by: Perry Yuan <perry.yuan@amd.com>