drm/amd/autoconf: fix the sled15.1 compiling error
  CC [M]  /var/lib/dkms/amdgpu-pro/1.0/build/amd/amdgpu/../display/amdgpu_dm/amdgpu_dm_debugfs.o
/var/lib/dkms/amdgpu-pro/1.0/build/amd/amdgpu/../display/amdgpu_dm/amdgpu_dm.c: In function ‘dm_atomic_get_state’:
/var/lib/dkms/amdgpu-pro/1.0/build/amd/amdgpu/../display/amdgpu_dm/amdgpu_dm.c:2037:58: error: ‘struct amdgpu_display_manager’ has no member named ‘atomic_obj’
  priv_state = drm_atomic_get_private_obj_state(state, &dm->atomic_obj);
                                                          ^~
/var/lib/dkms/amdgpu-pro/1.0/build/amd/amdgpu/../display/amdgpu_dm/amdgpu_dm.c: In function ‘dm_atomic_get_new_state’:
/var/lib/dkms/amdgpu-pro/1.0/build/amd/amdgpu/../display/amdgpu_dm/amdgpu_dm.c:2057:23: error: ‘struct amdgpu_display_manager’ has no member named ‘atomic_obj’
   if (obj->funcs == dm->atomic_obj.funcs)
                       ^~
/var/lib/dkms/amdgpu-pro/1.0/build/amd/amdgpu/../display/amdgpu_dm/amdgpu_dm.c: In function ‘dm_atomic_get_old_state’:
/var/lib/dkms/amdgpu-pro/1.0/build/amd/amdgpu/../display/amdgpu_dm/amdgpu_dm.c:2075:23: error: ‘struct amdgpu_display_manager’ has no member named ‘atomic_obj’
   if (obj->funcs == dm->atomic_obj.funcs)
                       ^~
/var/lib/dkms/amdgpu-pro/1.0/build/amd/amdgpu/../display/amdgpu_dm/amdgpu_dm.c: In function ‘dm_atomic_duplicate_state’:
/var/lib/dkms/amdgpu-pro/1.0/build/amd/amdgpu/../display/amdgpu_dm/amdgpu_dm.c:2091:55: error: passing argument 2 of ‘__drm_atomic_helper_private_obj_duplicate_state’ from incompatible pointer type [-           Werror=incompatible-pointer-types]
  __drm_atomic_helper_private_obj_duplicate_state(obj, &new_state->base);
                                                       ^
In file included from /var/lib/dkms/amdgpu-pro/1.0/build/include/kcl/kcl_drm.h:11:0,
                 from /var/lib/dkms/amdgpu-pro/1.0/build/amd/amdgpu/../backport/backport.h:9,
                 from <command-line>:0:
/usr/src/linux-4.12.14-195/include/drm/drm_atomic_helper.h:187:6: note: expected ‘struct drm_private_state *’ but argumen

This reverts commit a93144617d2be670ca77756ae9e6e20da917af1f.

Change-Id: If38a75a3eda8cbe8a40dbac654569ff191276938
Signed-off-by: Slava Grigorev <slava.grigorev@amd.com>
Signed-off-by: Anatoli Antonovitch <anatoli.antonovitch@amd.com>
Signed-off-by: chen gong <curry.gong@amd.com>
Signed-off-by: Yifan Zhang <yifan1.zhang@amd.com>
Reviewed-by: Flora Cui <flora.cui@amd.com>