Update config files.
Disable CONFIG_DRM_I915_WERROR, i.e. -Werror in i915. It causes build
failures in -syzkaller flavor due to a bit oversized frames:
drivers/gpu/drm/i915/intel_dpll_mgr.c:1548:1: error: the frame size of 2240 bytes is larger than 2048 bytes

suse-commit: 5fc7b327348be7e69f51d2e31d84077acef7aabd