config.conf: disable syzkaller
I doubt anybody else (other than me) uses the flavor, so save a lot of
build resources by this. Leaving syzkaller configs and stuff in place
so people still can build it if they want.

The build is currently broken, so this "fixes" it too:
ERROR: "__sanitizer_cov_trace_cmpd" [drivers/gpu/drm/amd/amdgpu/amdgpu.ko] undefined!
ERROR: "__sanitizer_cov_trace_cmpf" [drivers/gpu/drm/amd/amdgpu/amdgpu.ko] undefined!

suse-commit: bdee95fe5329cc2eacefee4c70c51bee874ab1c3