drm: fix warning for missing vunmap
In file included from drivers/char/drm/drmP.h:795,
                 from drivers/char/drm/drm_dma.c:36:
drivers/char/drm/drm_memory.h: In function `drm_ioremapfree':
drivers/char/drm/drm_memory.h:191: warning: implicit declaration of function
`vunmap'

Signed-off-by: Andrew Morton <akpm@osdl.org>
Signed-off-by: Dave Airlie <airlied@linux.ie>