drm/amd/amdgpu: Fix logic bug in fatal error handling
CC      drivers/gpu/drm/amd/amdgpu/amdgpu_ras.o
drivers/gpu/drm/amd/amdgpu/amdgpu_ras.c:2567:28: error: bitwise or with non-zero value always evaluates to true [-Werror,-Wtautological-bitwise-compare]
              if (adev->ras_hw_enabled | AMDGPU_RAS_BLOCK__DF)
                  ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~

Presumably the author intended to test if AMDGPU_RAS_BLOCK__DF
bit was set if ras is enabled, so that's what I'm changing the
code to. Hopefully to do the right thing.

Fixes: 5778b47626b51 ("drm/amdgpu: Add fatal error handling in nbio v4_3")

Cc: Christian König <christian.koenig@amd.com>
Cc: Alex Deucher <alexander.deucher@amd.com>
Cc: Mario Limonciello <mario.limonciello@amd.com>
Cc: Hawking Zhang <Hawking.Zhang@amd.com>
Cc: Candice Li <candice.li@amd.com>
Signed-off-by: Srinivasan Shanmugam <srinivasan.shanmugam@amd.com>
Reviewed-by: Mario Limonciello <mario.limonciello@amd.com>